In [1]:
import pandas as pd
import sklearn
from dateutil import parser
from sklearn.linear_model import LogisticRegression,LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from xgboost import XGBClassifier

In [2]:
categorical_category = ["main_category" , "currency" , "state", "country"]
features = ["main_category" , "currency" , "country","goal" , "pledged","backers","days_apart"]
label = "state"
df = pd.read_csv("../Data/ks-projects-201801.csv")
X = df

In [3]:
def date_time():
    days_apart = []
    launched = df["launched"].values
    i = 0
    deadline = df ["deadline"].values
    for x in launched:
        days_apart.append((parser.parse(deadline[i]) - parser.parse(x)).days)
        i = i +1
    return days_apart

In [4]:
df["days_apart"] = date_time()

In [5]:
le = LabelEncoder()
for x in categorical_category:
    df[x] = le.fit_transform(df[x].values)
df

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,days_apart
0,1000002330,The Songs of Adelaide & Abullah,Poetry,12,5,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,1,0,9,0.0,0.0,1533.95,58
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,6,13,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,1,15,22,100.0,2421.0,30000.00,59
2,1000004038,Where is Hank?,Narrative Film,6,13,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,1,3,22,220.0,220.0,45000.00,44
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,10,13,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,1,1,22,1.0,1.0,5000.00,29
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,6,13,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,0,14,22,1283.0,1283.0,19500.00,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
378656,999976400,ChknTruk Nationwide Charity Drive 2014 (Canceled),Documentary,6,13,2014-10-17,50000.0,2014-09-17 02:35:30,25.0,0,1,22,25.0,25.0,50000.00,29
378657,999977640,The Tribe,Narrative Film,6,13,2011-07-19,1500.0,2011-06-22 03:35:14,155.0,1,5,22,155.0,155.0,1500.00,26
378658,999986353,Walls of Remedy- New lesbian Romantic Comedy f...,Narrative Film,6,13,2010-08-16,15000.0,2010-07-01 19:40:30,20.0,1,1,22,20.0,20.0,15000.00,45
378659,999987933,BioDefense Education Kit,Technology,13,13,2016-02-13,15000.0,2016-01-13 18:13:53,200.0,1,6,22,200.0,200.0,15000.00,30
378660,999988282,Nou Renmen Ayiti! We Love Haiti!,Performance Art,0,13,2011-08-16,2000.0,2011-07-19 09:07:47,524.0,1,17,22,524.0,524.0,2000.00,27

In [6]:
X =  df[features]
y = df[label]
train_x,test_x,train_y,test_y = train_test_split(X,y,test_size=0.4)

In [7]:
model = RandomForestClassifier()
model.fit(train_x,train_y)

RandomForestClassifier()

In [9]:
y_pred = model.predict(test_x)
y_pred_prob = model.predict_proba(test_x)
score = sklearn.metrics.accuracy_score(y_pred,test_y)
print("accuracy :" , sklearn.metrics.accuracy_score(y_pred,test_y))